services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./llm_app:/llm_app